work_dir: exp/seg
run_name: b0
rich_logging: true

tb:
  name: tb_logs
  log_graph: true

csv:
  name: csv_logs

checkpoints:
  filename: checkpoint-{epoch:02d}-{mIoU:.2f}
  monitor: val/iou
  mode: max
  save_top_k: 5
  every_n_epochs: 5

trainer:
  precision: 16-mixed
  max_epochs: 80
  enable_checkpointing: true
  check_val_every_n_epoch: 5

segcore:
  
  example_input_array: [1, 3, 1024, 2048]
  
  dataset:
   root: data/cityscapes/
   train_size: [1024, 1024]
   test_size: [1024, 2048]
   mean: [0.485, 0.456, 0.406]
   std: [0.229, 0.224, 0.225]
   ignore_index: 255
   class_mapping: { -1: 255, 0: 255, 1: 255, 2: 255, 3: 255, 4: 255, 5: 255, 6: 255, 7: 0, 8: 1, 9: 255, 10: 255, 11: 2, 12: 3, 13: 4, 14: 255, 15: 255, 16: 255, 17: 5, 18: 255, 19: 6, 20: 7, 21: 8, 22: 9, 23: 10, 24: 11, 25: 12, 26: 13, 27: 14, 28: 15, 29: 255, 30: 255, 31: 16, 32: 17, 33: 18 }
   class_names: ["road", "sidewalk", "building", "wall", "fence", "pole", "traffic_light", "traffic_sign", "vegetation", "terrain", "sky", "person", "rider", "car", "truck", "bus", "train", "motorcycle", "bicycle"]
   n_classes: 19

  dataloader:
    train:
      batch_size: 8
      num_workers: 4
    val:
      batch_size: 1
      num_workers: 4

  criterion:
    ohem_ratio: 0.8

  optimizer:
    name: AdamW
    lr: 0.0001
    weight_decay: 0.0001
    kwargs:
      betas: [0.9, 0.999]
      eps: 0.0000001
      amsgrad: false

  scheduler:
    name: warmupcosinelr
    kwargs:
      power: 0.9
      warmup_iter: 1000
      warmup_ratio: 0.05

  metrics:
    table_fmt: fancy_grid
    missing_val: "-"
    eps: 0.0000001
  